### ISSUE TITLE
goScroll方法为什么是private的?

### ISSUE THREAD

**Issue by Nobler** [xiwenhec/Banner#7]
pauseScroll方法是public的，goScroll为什么是private的。这样从外部停止滚动之后，就不能重新开始了。

**Comment by xiwenhec** [comment]
你好感谢你发现了这个问题,pauseScroll应该也是private的,这个问题应该是版本更新的时候遗忘.
设计的宗旨是不希望外界直接调用这两个方法实现滚动的开始和暂停

**Comment by Nobler** [comment]
@xiwenhec 为什么要隐藏掉这两个方法呀？
我看到你是通过Banner的可见性，去开始和暂停滑动的。但是我现在是在fragment里面使用Banner，隐藏掉当前fragment的时候，Banner仍然是可见的，这个时候只能调用pause去停止滑动。

**Comment by xiwenhec** [comment]
恩恩,设计的想法是想类似于Glide原理,使Banner自动绑定Activity或Fragment的生命周期,实现暂停和滚动,由于代码量会增大很多,所以没有实现,考虑一下这两个方法是应该公开,thank you

**Comment by Nobler** [comment]
@xiwenhec 嗯，我是青睐于你参考listview的数据刷新方式，灵活性很高😁
